version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /episode
    schedule:
      interval: weekly
    groups:
      episode:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /library
    schedule:
      interval: weekly
    groups:
      library:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /mpv-launcher
    schedule:
      interval: weekly
    groups:
      mpv-launcher:
        patterns: ["*"]
